import jwt from "jsonwebtoken";
import { verifyToken } from "@/utils/verifyToken.js";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export function verifyToken(token: string): { id: string; username: string; email: string } | null {
    try {
        if (!process.env.TOKEN_SECRET) {
            throw new Error("TOKEN_SECRET is not defined in the environment variables");
        }

        const decoded = jwt.verify(token, process.env.TOKEN_SECRET) as {
            id: string;
            username: string;
            email: string;
        };

        return decoded;
    } catch (error) {
        console.error("Invalid token:", error.message);
        return null;
    }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
